all:
	g++ -O3 -std=c++11 truss_decomposition.cc truss_decomposition_host.cc -o td

debug:
	g++ -g -std=c++11 truss_decomposition.cc truss_decomposition_host.cc -o td

# cpu:
# 	g++ -O3 -std=c++11 truss_decomposition_cpu_v2.cc -o td_cpu

# hash:
# 	g++ -std=c++11 hash_test.cc -o hash_test

clean:
	rm -rf td
