all:
	g++ -std=c++11 truss_decomposition.cc truss_decomposition_host.cc -o td

debug:
	g++ -g -std=c++11 truss_decomposition.cc truss_decomposition_host.cc -o td

hash:
	g++ -std=c++11 hash_test.cc -o hash_test

clean:
	rm -rf td
